before:
  hooks:
    - go mod tidy
builds:
  - id: glinet
    binary: glinet
    main: ./cmd/glinet
    ldflags:
      - -s
      - -w
      - -X main.version={{.Summary}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
brews:
  - name: glinet
    goarm: "6"
    goamd64: v3
    tap:
      owner: kazhuravlev
      name: homebrew-glinet
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kazhuravlev/glinet/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: kazhuravlev+goreleaserbot@fastmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/kazhuravlev/glinet"
    description: "Console client for GL.Inet routers"
    license: "MIT"
    test: |
      system "#{bin}/glinet help"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
